Description of nt_mmat
Home > NoiseTools > nt_mmat.m
nt_mmat
PURPOSE
y=nt_mmat(x,m) - matrix multiplication (with convolution)
SYNOPSIS
function y=nt_mmat(x,m)
DESCRIPTION
y=nt_mmat(x,m) -  matrix multiplication (with convolution)
  y: result
  x: input data (2D or more)
  m: matrix to apply (2D: right multiply, 3D: same with convolution)
  If m is 3D, the last index (k) is lag.
CROSS-REFERENCE INFORMATION
This function calls:
nt_fold y=fold(x,epochsize) - fold 2D to 3D
nt_mmat y=nt_mmat(x,m) - matrix multiplication (with convolution)
nt_unfold y=nt_fold(x) - unfold 3D to 2D
This function is called by:
nt_bias_cluster [c0,c1,A,todss,pwr0,pwr1]=nt_bias_cluster(x,dsr,flags) - cluster covariance
nt_cluster_jd [IDX,todss,SCORE]=nt_cluster_jd(x,dsr,flags,init) - cluster with joint diagonalization
nt_cluster_jd_old [A,todss]=nt_cluster_jd(x,dsr,flags) - cluster with joint diagonalization
nt_enforce_stationarity y=nt_enforce_stationarity(x,DSR,thresh) - locally project out non-stationary components
nt_hi_amp y=nt_hi_amp(x) - decompose into high-amplitude components
nt_kurtosis [todss,K]=nt_kurtosis(x,nIterations,exponent,w,smooth)- find high-kurtosis components
nt_mmat y=nt_mmat(x,m) - matrix multiplication (with convolution)
nt_narrowband_scan A=nt_narrowband_scan(x,freqs,sr,Q,plotflag) - scan for narrowband components using DSS
nt_pca_kmeans [topcs,pwr]=nt_pca_kmeans(x,nkeep) - PCA preceded by kmeans for speed
nt_peaky [tocomps,ii]=nt_peaky(c,x,T,nSmooth) - find components that maximize peakiness
nt_qca [squares,quads,D]=nt_qca(x,npcs,nsmooth,nquads) - maximize induced power using quadratic component analysis
nt_qca0 [tosquares,quads,D]=nt_qca0(x,npcs,nsmooth,nquads) - maximize induced power using quadratic component analysis
nt_qca02 [tosquare,quad,tosquare2,quad2,D]=nt_qca02(x,npcs,nsmooth) - maximize induced power using quadratic component analysis
nt_qca2 [square,quad,square2,quad2,D]=nt_qca(x,npcs,nsmooth) - maximize induced power using quadratic component analysis
nt_qpca [squares,quads]=nt_qpca(x,npcs,nsmooth,nquads) - quadratic PCA
nt_qpca0 [tosquares,quads,D]=nt_qpca0(x,npcs,nsmooth,nquads) - quadratic PCA
nt_sns3 [y,w]=nt_sns2(x,thresh) - sensor noise suppression, new version
nt_split_jd [idx,score_vector,todss]=nt_split_dss(x,thresh,depth) - segmentation based on joint diagonalization
SUBFUNCTIONS
function x=nt_mmat0(x,m)
SOURCE CODE
function y=nt_mmat(x,m)
%y=nt_mmat(x,m) -  matrix multiplication (with convolution)
%
%  y: result
%
%  x: input data (2D or more)
%  m: matrix to apply (2D: right multiply, 3D: same with convolution)
%
%  If m is 3D, the last index (k) is lag.
if nargin<2; error('!'); end
if ndims(x)>3
    % concatenate the last dimensions, process, then de-concatenate
    sz=size(x);
    x=reshape(x,[sz(1),sz(2),prod(sz(3:end))]);
    x=nt_mmat(x,m);
    x=reshape(x,[size(x,1),sz(2),sz(3:end)]);
else
    if ndims(m)==2;
        % no convolution
        y=nt_mmat0(x,m);
    else
        [nRows,nCols,nLags]=size(m);
        [nSamples,nChans,nTrials]=size(x);
        if nChans~=nRows;
            error('ncols(x) ~= nrows(m)');
        end
        % convolution: for each k, multiply x by m(:,:,k) and add with
        % shift of (k-1)
        y=zeros(nSamples+nLags-1,nCols,nTrials);
        for iLag=1:nLags
            y(iLag:iLag+nSamples-1,:,:) = y(iLag:iLag+nSamples-1,:,:) + nt_mmat0(x,m(:,:,iLag));
        end
    end
end
function x=nt_mmat0(x,m)
x=nt_fold(nt_unfold(x)*m,size(x,1));