Description of nt_pcarot
Home > NoiseTools > nt_pcarot.m
nt_pcarot
PURPOSE
[topcs,eigenvalues]=pcarot(cov,N) - PCA matrix from covariance
SYNOPSIS
function [topcs,eigenvalues]=nt_pcarot(cov,N)
DESCRIPTION
 [topcs,eigenvalues]=pcarot(cov,N) - PCA matrix from covariance
  topcs: PCA rotation matrix
  eigenvalues: PCA eigenvalues
  cov: covariance matrix
  N: eigs' K parameter (if absent: use eig)
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
nt_dss0 [todss,pwr1,pwr2]=nt_dss0(c0,c1,keep1,keep2) - dss from covariance
nt_pca [z,idx]=nt_pca(x,shifts,nkeep,threshold,w) - time-shift pca
nt_pca0 [topcs,pwr]=nt_pca0(x,shifts,nkeep,threshold,w) - time-shift pca
nt_pca_nodemean [z,idx]=nt_pca_nodemean(x,shifts,keep,threshold,w) - time-shift pca
nt_qpca0 [tosquares,quads,D]=nt_qpca0(x,npcs,nsmooth,nquads) - quadratic PCA
nt_regcov r=nt_regcov(cxy,cyy,keep,threshold) - regression matrix from cross covariance
nt_sns0 r=nt_sns0(c,nneigbors,skip,wc) - sensor noise suppression
nt_sns2 [y,w]=nt_sns2(x,thresh) - sensor noise suppression, new version
nt_sns3 [y,w]=nt_sns2(x,thresh) - sensor noise suppression, new version
nt_sns3_old [y,w]=nt_sns2(x,thresh) - sensor noise suppression, new version
nt_sns4 [y,w]=nt_sns2(x,thresh) - sensor noise suppression, new version
SOURCE CODE
function [topcs,eigenvalues]=nt_pcarot(cov,N)
% [topcs,eigenvalues]=pcarot(cov,N) - PCA matrix from covariance
%
%  topcs: PCA rotation matrix
%  eigenvalues: PCA eigenvalues
%
%  cov: covariance matrix
%  N: eigs' K parameter (if absent: use eig)
%
% NoiseTools
if nargin >1 && ~isempty(N);
    [V, S] = eigs(cov,N) ;
else
    [V, S] = eig(cov) ;
end
V=real(V);
S=real(S);
[eigenvalues, idx] = sort(diag(S)', 'descend') ;
topcs = V(:,idx);