Description of nt_spect_plot
Home > NoiseTools > nt_spect_plot.m
nt_spect_plot
PURPOSE
nt_spect_plot - plot power spectrum
SYNOPSIS
function varargout=nt_spect_plot(x,varargin)
DESCRIPTION
nt_spect_plot - plot power spectrum
  The power spectral densities of all columns (pages, etc.) are calculated
  and added.  The result is divided by the number of columns and either
  plotted or returned.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
nt_bias_cluster [c0,c1,A,todss,pwr0,pwr1]=nt_bias_cluster(x,dsr,flags) - cluster covariance
nt_cluster_jd [IDX,todss,SCORE]=nt_cluster_jd(x,dsr,flags,init) - cluster with joint diagonalization
nt_cluster_jd_old [A,todss]=nt_cluster_jd(x,dsr,flags) - cluster with joint diagonalization
nt_spect_plot2 nt_spect_plot2 - plot power spectrum
nt_yulewalk_whiten [y,B,A]=nt_yulewalk_whiten(x,order,freqs) - whiten spectrally
SOURCE CODE
function varargout=nt_spect_plot(x,varargin)
%nt_spect_plot - plot power spectrum
%
%  The power spectral densities of all columns (pages, etc.) are calculated
%  and added.  The result is divided by the number of columns and either
%  plotted or returned.
if numel(x)==0; error('!'); end
N=numel(x);
ncols=N/size(x,1);
x=reshape(x,size(x,1),ncols);
[pxx,f]=pwelch(x(:,1),varargin{:});
for k=1:ncols
    [a,b]=pwelch(x(:,k),varargin{:});
    pxx=pxx+a;
end
pxx=pxx/ncols;
if nargout == 0;
    plot(f,abs(pxx).^0.5);
    set(gca,'yscale','log');
    xlim([f(1) f(end)]);
    xlabel('Hz'); ylabel('Hz^{-0.5}');
    varargout={};
else
    varargout={pxx,f};
end